/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib0F4Z0hESWlUQnowM2R1MW1DNlNCVEV4cGpBRTNPWWZxd3Y0dEpIRmtIaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib1V1YXhSbzllZzlCc1Qva25CT1Vibm1HSnJHRGJzaGJoeFZIdUwveUZBbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI4SHJQZmZadG5IdHBzQkZIVko5dVBUQTNJeG1ZUkNTZW9MUDhmUWo3RUU4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhdnFpU3ltdGtNdGZud1Y5L3pHUEVLYkoxK1F0cWMyVFNmQ3hZN3FmaWtNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9JMEpLQ3N1aGRMb0JSREo3WkdTSFVvR0xLa1ZUd21NZDJXVGlKb0krRjA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IllxQ3Flbk55T3kvbFJXUStGQzFwZC8rSDlWODhTQSs2QWdrOUNROGRXd3c9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0ZpRmVIRXdpVDZVUUNWSFNyZnhDM0psTXU4VURCdHJkTVFZTk9Lc2UwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNFQ2K3F2VHRLK3F6TDQzc3ptaEYrZFNKMWNhOGpaZGFITFFYWnJxUEYzZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjR0Nk5DTHlFU1ZQU0R3Mmo0VEYwZzFrTUxZT0doQ21UdDUwYzZGUi84MXgwRmkxa0EvMTAxOHYxTE1hWlVmYm9saHF4TzR6VFhQY1BCZC9XbWRLY2d3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTg0LCJhZHZTZWNyZXRLZXkiOiI1dUZ0VG5EczZKMUFLZkhDMFgrOU0xU3FUdVlsdXhoMEhYbU96dXdSMVRVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1Njc1MTYxNzc4OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1OUZENUI4NjkyQkNBNDVFOERBQTIyMUIzMkQ3ODM3QSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMyMzExMjExfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJNVHBreE1qQlFnbW1PUXNSWlNxLVZnIiwicGhvbmVJZCI6Ijc3Yzk5MmZmLTZkYWYtNDRiMC05MzJmLTg4ZDM5MWVmODEyYSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCeG5CbWsrVERDeUg5ZkNZMmFWdFRJb2h3Mjg9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic3IxUU5tb1krTHhiejZBR1JNM1dlTGgrbXpJPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IksxNktYSDJTIiwibWUiOnsiaWQiOiIyNTY3NTE2MTc3ODg6MjJAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ042OHNiY0NFSm54ZzdvR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImF4Znh4eXZJUzgxWnFDL3FmbWN1ZU1WVWtXTG5vVmo5d3IzLzE4d2xTUTQ9IiwiYWNjb3VudFNpZ25hdHVyZSI6IllaTVkzQ1lnOXlRTDJZWFk0VUJGb3JxUU15WU9hNXoyZndwMm94QTNGSDkzdVNqRnAwMStFU2pBWU9JRmNjTnJRZzc4SFF1eS9LeVptWjd4RkE0NENBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiIrelltVk5raVp1TVhOd1lITW5ZbFl4MVRaM3JmS1JvTUZMUUQwS09lYXluczlVVm1FRnMyaVRlakc5bWNIU0E2WTZvbTYzYjlkQ3BSeFRHQndmQjlqZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1Njc1MTYxNzc4ODoyMkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJXc1g4Y2NyeUV2TldhZ3Y2bjVuTG5qRlZKRmk1NkZZL2NLOS85Zk1KVWtPIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMyMzExMjA3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUxPTCJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'ZIK BUG BOT🐛-MD';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
