/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY09TMjlKR0RnNmFaTGZrZ25RckxTV2NsVlZDcVQ4TWhPb2s4VHZpM2htbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZVgxSnZMZUpyREZpZExWZDVrMU1VTUdDOHNoZTk4RW11WkFKekJPRUgxMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlTjk4eHFrMGs5L0dDTDRkZWg3SldlSlkvQWxKbFEwUW14aDVNRk91Skc0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvRmhVYzR5bVhISzFRL3BpQ3RvZGwzOTMxVTMxVjlsM294eW5HblhrbkRJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVGMTZabWNGdll4bTQ3a2gwS3lBcU9wRDdvbThjMU1BSFd1STVoUldUbUE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImhPdU83RW9VcDJOanAyNm80Y2pNd0ZZcStYT3NJQVVpQllYWmVkaTdaQ0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0N3UWw3MlYwOGpHKzBPMFZCVGdua2lrbXdxN0RHRlZMeEJrNFZuOCtFdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibkYreThLN2RnMkMvTHZvVldxemUrMSt2QzdWaVZ1MHNMa3lGV2RrQVRVRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlJTakNiRFVJRVJ4aDNxWk9mZTl5b3lwbm5QZTg5Ry9BVWVHZ0Vad2pZUWlKaWpHN1RsNUNqZ0gzcFJiNmVkVXRBUHJSTjlWOXVQT01NNXY4RHU1MmdBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTg3LCJhZHZTZWNyZXRLZXkiOiJCdGdUSXlHbzM2Wk9vcEM0Ym9SaVFXM05lSEErNXI5eG54MkZFUVZDVWpFPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1Njc1MTYxNzc4OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIwNTM2MTYzMDJCQzAzOUE1NjAxODlBQkMyNjA3NzcwNiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMzNzY1MDYxfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTY3NTE2MTc3ODhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRUYyMTVDNUI5RTJGODJFNzFEMTc4RDQ0RUY5REI5OEEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMzc2NTA2Mn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU2NzUxNjE3Nzg4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkI3RTNFODE3MUYyRTI3QTRENUYzNjM0MEQ1ODM0RTUyIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzM3NjUwNjR9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1Njc1MTYxNzc4OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI0RDZDREFGMzI2REQ5NTU5MzIzMjMyNkU1REUyMkQ0NSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMzNzY1MDY0fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJEYzY3T0QxU1R3LXlxSjZibldNNmRBIiwicGhvbmVJZCI6IjA5ZDJjNDhjLWFjNjAtNGVlMi1hYWM3LTk1ZGMwMzhhOWU0YyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFbW9RVXh2MGc2S0FWczhPdmN6M3I5MVdoc0U9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVTNUbis4NGM5aTlYQXB1czZXWUdUVTVkNUM0PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlBQQlhQR1hOIiwibWUiOnsiaWQiOiIyNTY3NTE2MTc3ODg6MjlAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ01TdDY1SUJFTGJQM0xvR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImtsNUwydU03Y0p0UzFyMkw1clNsTU52cEtXemN1YlRPUGxoWkxLcVN0MGs9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjNpSXZrTHJFM2FsUFZZdllNbjZxazBtN2Q1Qk82VDd0QVRNb1d2TnJxdFVDaDRWV2phUjZXZk1kOWNpWk5tZTJ2b29WVzExUmFYUEtlVXBNNzJwS0FBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJHTThuZFZ4THJXREh1YVM5em5RSUdTRlZ5Wk9GRnhVMytaTDRDK3R2SUZ3MWsxS2hxeHhnQ0V3VHV5Q3NzOG53YVV5K2ZoTHF5VUZYL2R3ekpNc3lqUT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1Njc1MTYxNzc4ODoyOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJaSmVTOXJqTzNDYlV0YTlpK2EwcFREYjZTbHMzTG0wemo1WVdTeXFrcmRKIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMzNzY1MDU5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUU0RSJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "256";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevKeith = dev.split(",");
const botname = process.env.BOTNAME || 'ZIK ☠️ DEATH BOT';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const autoreact = process.env.AUTOREACT || 'true';
const antibot = process.env.ANTIBOT || 'true';
const anticall = process.env.ANTICALL || 'false';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  autoreact,
  mode,
  prefix,
  anticall,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevKeith,
  gcpresence,
  antionce,
  antibot,
  session,
  antitag,
  antidelete
};
