/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUlwYWI4UDREd0RpQlJxcTdraGFGSW1RRkxKNXJVSVVxYWRVQVVTNGpHbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTk5XRm01a2dvZkxzSHYrNDNuaitZVmF3MDB5TEQ2UmsrS29jQ1RUWUlIVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJJR3dpWlZaWjdBRXdQNStpZ2lMWGVKelJ0Ly9nTGxKSTc2ak13L3lYcFVVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJta250cTA1eEdhbUpxMGlTc2xObHNIYzlXY25uSjMxbjJIZzRNUUVjNTNnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFDWmgrbFB6dmNiaTV2dWd2MVZ4OWQ4S0xDUlBndVBFTzh6WmlkZGwvMk09In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdjMWxsdUxpOHdLK0loQmh2bXNTWE9NUzlxQm9jM1hFRDBkaFN5Y2VwU0k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUo2TnZzS0xLY3dBQTdiK3BEYmdZSjFsa1VIaW9LT0p4SlVxR2N4Ry9scz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUXVyZFo4QUxyZ1BiNXBKSkJlcjFjcUh2NnNvZ2JuTnJCVjdxMDQ4WE5SOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRwMVFRelZFVDgzc1c0NTRrekxwSGszYjZUM1IyYWZSaTJDNkozbVEvM3A5bUw5ZG01Z29RSmRCcGtldWlPa0xSSEFWbGYxTTZlZkpVeEhZU05RSGp3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjEsImFkdlNlY3JldEtleSI6Ii9Zd1RpYXlrWU0zbGF1OFVreUFjV08wc3JHRDEzaUV4QVB6WXhkUTcyZXM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Ik9PUHNEZG16UzFtNEdIQXpIal9saEEiLCJwaG9uZUlkIjoiNGUwOTE2YTktY2VhMC00MjM0LWE5MWMtODFlMGNjNmZmZGRlIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9NeE9SNlExbU9Ybk03ajJjRkhqWm94dTV5UT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwblh5RFA3ZkxmZWx2L2RTM0VsWWpUS21xMGc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiQVhWUzFLRkQiLCJtZSI6eyJpZCI6IjI1Njc1MTYxNzc4ODoxNkBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSS9UdU5NSEVQL2d0cmtHR0FvZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoicDVuSzZVblJmMk90UlN2b29VS05OMGkvV1hwQ0dWS016aUkyVlZxaWJnND0iLCJhY2NvdW50U2lnbmF0dXJlIjoiMGFvWmcvYW9aanhMQWl3aVRDNmV4bzVCK0J3WlRMdzR5U2VxRGczTXBLTkE1VjVIM3V0bHRSY0N5ZVlYK3VodXh5MzB0R3pFckpFek1Nd2Zhd0VaRFE9PSIsImRldmljZVNpZ25hdHVyZSI6InRUZDdWQ2ZIdWQ3YytQUytoRjhXWUFsOFJQMkFubkpXaWJEQ2Vhd1V4VXEweWNiY1JjcVgyYjc3cVBrYXc4dXJQbXBUMmcwMjBld2M3Ry9XNnoxUGpRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU2NzUxNjE3Nzg4OjE2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmFlWnl1bEowWDlqclVVcjZLRkNqVGRJdjFsNlFobFNqTTRpTmxWYW9tNE8ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzEwNDc1NjUsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTEpDIn0=';

const prefix = process.env.PREFIX || ',';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
